[[bitwarden_cli]]
arch = "x86_64"
git-tree-sha1 = "5733244572ae3daa9084c461424355284512f029"
os = "macos"

    [[bitwarden_cli.download]]
    sha256 = "9030df6f17a6ae5ad38389267611f378f54e009d1425a337fe61e6c717846b44"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v2025.1.3+0/bitwarden_cli.v2025.1.3.x86_64-apple-darwin.tar.gz"
[[bitwarden_cli]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fc58d9de8d3c346370e236f34844f7bb3c50792"
libc = "glibc"
os = "linux"

    [[bitwarden_cli.download]]
    sha256 = "2a700a1c97bb8225b402a7e010476ef5fbfb3f49c4678220e513421b1112ff7b"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v2025.1.3+0/bitwarden_cli.v2025.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[bitwarden_cli]]
arch = "x86_64"
git-tree-sha1 = "3ec52160b771fae1a7e54e2c5aa37b015bc8715c"
os = "windows"

    [[bitwarden_cli.download]]
    sha256 = "d124062f9d0d2effcf87062958a6e622df858c0666320bec41f4841cfcf66202"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v2025.1.3+0/bitwarden_cli.v2025.1.3.x86_64-w64-mingw32.tar.gz"
