[[bitwarden_cli]]
arch = "x86_64"
git-tree-sha1 = "37b6827157a44efe35be9e8dfaf4a0948b1462f9"
os = "macos"

    [[bitwarden_cli.download]]
    sha256 = "b21c7d7219086d41e8448c53013a56f98d79d6c6307be2f295e9b046fef954f6"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v1.17.1+0/bitwarden_cli.v1.17.1.x86_64-apple-darwin.tar.gz"
[[bitwarden_cli]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca44511d893f125c6bd18453f481972d6a341575"
libc = "glibc"
os = "linux"

    [[bitwarden_cli.download]]
    sha256 = "dff5866251f6b283c6a232baa96eaa4cf9651c8111701ce6b3bf3cee781cf720"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v1.17.1+0/bitwarden_cli.v1.17.1.x86_64-linux-gnu-cxx11.tar.gz"
[[bitwarden_cli]]
arch = "x86_64"
git-tree-sha1 = "a9b5ea49d42cbd291b866e295baa7ad47a7c8e8d"
os = "windows"

    [[bitwarden_cli.download]]
    sha256 = "0880311c0ca35545b11a59beb6174f5eb225f8d2bdcafbfe7448047eb9412903"
    url = "https://github.com/JuliaBinaryWrappers/bitwarden_cli_jll.jl/releases/download/bitwarden_cli-v1.17.1+0/bitwarden_cli.v1.17.1.x86_64-w64-mingw32.tar.gz"
